# This plabook will be run in the ec2-instance that packer will be creating and it will run this playbook in the local host


---
- hosts: localhost      
  become: true

  tasks:
    - block:     # setting blocks and rescue is to say if a task faild it she be rescue with it stopint the playbook from runx the rest of the tasks.
        - name: Install aptitude using apt
          apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

        - name: Install required system packages
          apt: name={{ item }} state=latest update_cache=yes
          loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

        - name: Add Docker GPG apt Key
          apt_key:
             url: https://download.docker.com/linux/ubuntu/gpg
             state: present

        - name: Add Docker Repository
          apt_repository:
             repo: deb https://download.docker.com/linux/ubuntu bionic stable
             state: present

        - name: Update apt and install docker-ce
          apt: update_cache=yes name=docker-ce state=latest

        - name: Install Docker Module for Python   # this task is set to fail for us know how "rescue works" it will faild 
          pip:                                     # because we don't have the package "pip" install yet
            name: docker                  # but when it failed it won't stop the script but instead it will go to the "rescue" and if we have set the recuse for "pip installation"
                                           # it will install "pip" and continue the script.
        - name: Docker group
          shell: |
                 sudo groupadd docker
                 sudo usermod -aG docker $USER
                 sudo systemctl enable docker

      rescue:        # here is our recuse 
        - name: You need to recover
          debug:
            msg: "It looks like PIP is not installed. You will need to install it"

        - name: Recovery block
          shell: |
            sudo apt update
            sudo apt install python3-pip


      
      
